### ISSUE TITLE
Technical viability #1

### ISSUE THREAD

**Issue by RamyaBandi** [SJSUFall2019-CMPE272/Automated-pet-surveillance#1]
In the abstract you have mentioned that you will be monitoring the pets using web cam, but the question here is, are you restricting the pets to stay at one place under cam surveillance to observe his abnormalities or are the pets allowed to move around the house or to other rooms?

**Comment by dnamrata7** [comment]
Current Implementation does not include multiple cameras. At Present, we are monitoring the pet at the place the device is situated.
