### ISSUE TITLE
#1Business value

### ISSUE THREAD

**Issue by dhanasreeA** [SJSUFall2019-CMPE272/Automated-pet-surveillance#2]
The project is a practical one given the fact that a lot of pet owners cannot stay at home and take care of the pets all the time. A concern about the project is:

1. Since you are using sensors, raspberry pie and motors we believe the project will get really expensive. Do you think people will be willing to spend that much?
 We spoke to three pet owners and two out of three mentioned that they wouldn't be willing to spend a lot of money on something they have already trained their pet for. 
Another mentioned that, since they would be away only for a few hours for work, they would prefer a pet care center in case they really need to watch their pet on some days, since that is a more viable option.

**Comment by dnamrata7** [comment]
The survey that you took cannot be generalized. Asking just 3 pet owners and generalizing it for the entire community would not be appropriate. 
And for the expensive part, the device price will be a one-time investment.
Considering the per hour charges for the pet care center, the proposed solution will prove itself to be a more efficient and cheaper option.
