### ISSUE TITLE
technical viability #2

### ISSUE THREAD

**Issue by RamyaBandi** [SJSUFall2019-CMPE272/Automated-pet-surveillance#3]
We feel the system which is proposed here is semi- supervised and hence not completely automated because the user needs to approve the feeding for the pet. There might arise a case where the user cannot access their mobile phones at that point of time, which will fail the main purpose of this project. We suggest you to develop a fully automated system which automatically delivers the pet requirements based on the needs without waiting for the pet owners response and also allowing the owner to monitor their pets closely.

**Comment by dnamrata7** [comment]
The current implementation handles automation , providing both automated feeding and User-controlled feeding.
