### ISSUE TITLE
#2Business value

### ISSUE THREAD

**Issue by dhanasreeA** [SJSUFall2019-CMPE272/Automated-pet-surveillance#4]
We looked up some links online and found similar motion sensor cameras and food dispensing machines. How is this project going to be different from the already existing systems? 

surveillance cameras:

https://www.amazon.com/Wansview-Wireless-Security-Surveillance-Monitor/dp/B075K89NTR/ref=sr_1_3?crid=22P3ZT6V985VV&keywords=pet+surveillance+camera&qid=1571875936&sprefix=pet+surve%2Caps%2C190&sr=8-3

food dispensing systems:

https://www.amazon.com/Furbo-Dog-Camera-Designed-Compatible/dp/B01FXC7JWQ/ref=sr_1_1?keywords=pet+surveillance+and+feeding&qid=1571875952&sr=8-1

**Comment by dnamrata7** [comment]
The mentioned alternatives provide much more expensive options without offering all the functionalities provided by our solution.
