### ISSUE TITLE
Technical Viability#3

### ISSUE THREAD

**Issue by RamyaBandi** [SJSUFall2019-CMPE272/Automated-pet-surveillance#5]
We feel this design is developed for owners who have single pets, as the sounds coming from one pet might interfere with other pets. If they have multiple pets, does the owner need to install different devices for different pets?

**Comment by dnamrata7** [comment]
The current functional scope entails only one type of pet (Dogs). The multiple dogs issue will not be encountered as the live streaming of pets will help the user to distinguish which specific pet is barking.
